= This Week in JBoss - January 6th 2022
Stefan Sitani
2022-1-6
:tags: quarkus, java, resteasy, camel, reactive, panache, hibernate

Happy new year, everyone! Welcome to the first JBoss weekly editorial of 2022.

== Release roundup

Here are the releases from the JBoss Community for this edition:

[square]
* link:https://quarkus.io/blog/quarkus-2-6-0-final-released/[Quarkus 2.6.0]

* link:https://camel.apache.org/blog/2021/12/camel-quarkus-release-2.6.0/[Camel Quarkus 2.6.0]


== New Book: Reactive Systems in Java

link:https://www.oreilly.com/library/view/reactive-systems-in/9781492091714/[Reactive Systems in Java], by Clement Escoffier and Ken Finnigan

In their new book, Clement Escoffier and Ken Finnigan take an in-depth look at reactive systems design make applications responsive, elastic, and resilient, and
explore event-driven architectures as a flexible and composable option for designing distributed systems. Full of practical examples, their new book helps developers bring these approaches together when designing applications with Quarkus. You can order your copy of _Reactive Systems in Java_ from O'Reilly Books.


== Simplify Java persistence using Quarkus and Hibernate Reactive

link:https://developers.redhat.com/articles/2022/01/06/simplify-java-persistence-using-quarkus-and-hibernate-reactive#[Simplify Java persistence using Quarkus and Hibernate Reactive] by Daniel Oh


== Getting started with Netty

link:http://www.mastertheboss.com/jboss-frameworks/netty/jboss-netty-tutorial/?utm_source=rss&utm_medium=rss&utm_campaign=jboss-netty-tutorial[Getting started with Netty] by Francesco Marchioni

In his tutorial, Francesco Marchioni shows how you can use the new reactive JAX-RS implementation in Quarkus to design non-blocking REST endpoints for your web services to increase the throughput of your applications, minimize their consumption of CPU and network resources, and achieve faster response times. Francesco also looks at how you can use map exception handlers to specific JAX-RS resource classes.

== Videos

Here's my pick of this week's YouTube videos:

* link:https://youtu.be/1_GUWDeQIsc[Drag and Drop your Quarkus Serverless App on the Developer Sandbox]


_That's all for today! Please join us again in two weeks for another round of our JBoss editorial!_
